'use strict';
const assert = require('assert');
const { classify, quality, isInjected, cleanUserText, redactExcerpt, render, renderEvidence } = require('./analyze-prompts');

assert(classify('전체 프로젝트 테스트를 다시 확인해 줘').includes('검증·재확인'));
assert(classify('기능을 구현하고 수정해 줘').includes('구현·수정'));
assert(quality('C:\\repo 프로젝트의 테스트를 실행하고 PASS 결과를 표로 보여 줘. 공개 파일에는 포함하지 마.').score >= 80);
assert(isInjected('<system-reminder>hidden</system-reminder>'));
assert.strictEqual(cleanUserText('<recommended_plugins>private</recommended_plugins>실제 요청'), '실제 요청');
assert.strictEqual(cleanUserText('<INSTRUCTIONS>rules</INSTRUCTIONS><environment_context>ctx</environment_context>실제 최종 요청'), '실제 최종 요청');
const redacted = redactExcerpt('C:\\Users\\person\\secret.txt https://private.example user@example.com sk-abcdefghijklmnop');
assert(!redacted.includes('person'));
assert(!redacted.includes('private.example'));
assert(!redacted.includes('user@example.com'));
assert(!redacted.includes('sk-abcdefghijklmnop'));
const secret = 'PRIVATE_PROMPT_SHOULD_NOT_APPEAR';
const html = render({ days: 30, generatedAt: '2026-09-07', tools: [{tool:'claude',sessions:1,prompts:1,responses:1,avgPromptChars:10,avgQuality:80,answerRate:100,evidenceRate:100,correctionSignals:0,intents:{'검증·재확인':1},commands:{'/verify':1},qualityChecks:{'목표 명확성':1},qualitySum:80}] });
assert(!html.includes(secret));
assert(html.includes('로컬 전용'));
const reportHtml = renderEvidence({days:30,generatedAt:'2026-09-07',tools:[{tool:'codex',sessions:1,prompts:1,responses:1,avgPromptChars:20,avgQuality:50,qualitySum:50,answerRate:100,toolRate:100,verifiedRate:100,answered:1,toolEvidence:1,verifiedEvidence:1,correctionSignals:0,excludedBootstrap:0,intents:{'검증·재확인':1},commands:{},qualityChecks:{'목표 명확성':1},evidenceRows:[{id:'codex-abc-1',timestamp:'2026-09-07',intent:'검증·재확인',excerpt:'테스트를 확인해 줘',specScore:50,missing:['완료 조건'],answered:true,toolUsed:true,verified:true,correction:false}]}]});
assert(reportHtml.includes('미교정 휴리스틱'));
assert(reportHtml.includes('codex-abc-1'));
assert(reportHtml.includes('지원하지 않는 주장'));
assert(reportHtml.includes('max-height:520px'));
assert(reportHtml.includes('position:sticky'));
assert(reportHtml.includes('family=Jua'));
assert(reportHtml.includes('Bean et al.'));
assert(reportHtml.includes('구성타당도'));
assert(reportHtml.includes('준거타당도'));
assert(reportHtml.includes('Cohen’s κ'));
assert(reportHtml.includes('현재 최종 판정'));
assert(reportHtml.includes('현재 데이터에 근거한 개선 의견'));
assert(reportHtml.includes('재사용 가능한 요청 형식'));
assert(reportHtml.includes('AI 최종 응답에 요구할 증거 형식'));
assert(reportHtml.includes('2311.07911'));
assert(reportHtml.includes('10.1145/3728922'));
console.log('PASS: prompt analysis unit checks');
